gem_10 = {
    1: 'Azurite',
    2: 'Banded Agate',
    3: 'Blue Quartz',
    4: 'Eye Agate',
    5: 'Hematite',
    6: 'Lapis Lazuli',
    7: 'Malchite',
    8: 'Moss Agate',
    9: 'Obsidian',
    10: 'Rhodochrosite',
    11: 'Tiger Eye',
    12: 'Turquoise'
}

gem_50 = {
    1: 'Bloodstone',
    2: 'Carnelian',
    3: 'Chalcedony',
    4: 'Chrysoprase',
    5: 'Citrine',
    6: 'Jasper',
    7: 'Moonstone',
    8: 'Onyx',
    9: 'Quartz',
    10: 'Sardonyx',
    11: 'Star rose quartz',
    12: 'Zircon'
}

gem_100 = {
    1: 'Amber',
    2: 'Amethyst',
    3: 'Chrysoberyl',
    4: 'Coral',
    5: 'Garnet',
    6: 'Jade',
    7: 'Jet',
    8: 'Pearl',
    9: 'Spinel',
    10: 'Tourmaline'
}

gem_500 = {
    1: 'Alexandrite',
    2: 'Aquamarine',
    3: 'Black Pearl',
    4: 'Blue Spinel',
    5: 'Peridot',
    6: 'Topaz'
}

gem_1000 = {
    1: 'Black Opal',
    2: 'Blue Sapphire',
    3: 'Emerald',
    4: 'Fire Opal',
    5: 'Opal',
    6: 'Star Ruby',
    7: 'Star Sapphire',
    8: 'Yellow Sapphire'
}

gem_5000 = {
    1: 'Black Sapphire',
    2: 'Diamond',
    3: 'Jacinth',
    4: 'Ruby'
}

art_25 = {
    1: 'Silver ewer',
    2: 'Carved bone statuette',
    3: 'Small gold bracelet',
    4: 'Cloth-of-gold vestments',
    5: 'Black velvet mask stitched with silver thread',
    6: 'Copper chalice with silver filigree',
    7: 'Pair of engraved bone dice',
    8: 'Small mirror set in a painted wooden frame',
    9: 'Embroidered silk handkerchief',
    10: 'gold locket with a painted portrait inside'
}

art_250 = {
    1: 'Gold ring set with bloodstones',
    2: 'Carved ivory statuette',
    3: 'Large gold bracelet',
    4: 'Silver necklace with gemstone pendant',
    5: 'Bronze crown',
    6: 'Silk robe with gold embroidery',
    7: 'Large well-made tapestry',
    8: 'Brass mug with jade inlay',
    9: 'Box of turquoise animal figurines',
    10: 'Gold bird cage with electrum filigree'
}

art_750 = {
    1: 'Silver chalice with moonstones',
    2: 'Sliver-plated steel longsword with jet set in hilt',
    3: 'Carved hard of exotic wood with ivory inlay and zirconb gems',
    4: 'Small gold idol',
    5: 'Gold dragon comb set with red garnets as eyes',
    6: 'Bottle stopper cork embossed with gold leaf and set with amethysts',
    7: 'Ceremonial electrum dagger with a black pearl in the pommel',
    8: 'Silver and gold brooch',
    9: 'Obsidian statuette with gold fittings and inlay',
    10: 'Painted gold war mask'
}

art_2500 = {
    1: 'Fine gold chain set with a fire opal',
    2: 'Old masterpiece painting',
    3: 'Embroidered silk and velvet mantle set with numerous moonstones',
    4: 'Platinum bracelet set with a sapphire',
    5: 'Embroidered glove set with jewel chips',
    6: 'Jeweled anklet',
    7: 'Gold music box',
    8: 'Gold circlet set with four aquamarines',
    9: 'Eye patch with a mock eye set in blue sapphire and moonstone',
    10: 'A necklace string of small pink pearls'
}

art_7500 = {
    1: 'Jeweled gold crown',
    2: 'Jeweled platinum ring',
    3: 'Small gold statuette set with rubies',
    4: 'Gold cup set with emeralds',
    5: 'Gold jewlery box with platinum filigree',
    6: 'Painted gold child sarcophagus',
    7: 'Jade game board with solid gold playing pieces',
    8: 'Bejeweled ivory drinking horn with gold filigree'
}

item_a = {
    range(1, 51): 'Potion of healing',
    range(51, 61): 'Spell scroll - cantrip',
    range(61, 71): 'Potion of climbing',
    range(71, 91): 'Spell scroll - 1st level',
    range(91, 95): 'Spell scroll - 2nd level',
    range(95, 99): 'Potion of greater healing',
    99: 'Bag of holding',
    100: 'Driftglobe'
}

item_b = {
    range(1, 15): 'Potion of greater healing',
    range(16, 22): 'Potrange of keys in dictionaryion of fire breath',
    range(23, 29): 'Potion of resistance',
    range(30, 34): 'Ammunition, +1',
    range(35, 39): 'Potion of animal friendship',
    range(40, 44): 'Potion of hill giant strength',
    range(45, 49): 'Potion of growth',
    range(50, 54): 'Potion of water breathing',
    range(55, 59): 'Spell scroll - 2nd level',
    range(60, 64): 'Spell scroll - 3rd level',
    range(65, 67): 'Bag of holding',
    range(68, 70): 'Keoghtom ointment',
    range(71, 72): 'Oil of slipperiness',
    range(74, 75): 'Dust of disappearance',
    range(76, 77): 'Dust of dryness',
    range(78, 79): 'Dust of sneezing and choking',
    range(80, 81): 'Elemental gem',
    range(82, 83): 'Philter of love',
    84: 'Alchemy jug',
    85: 'Cap of water breathing',
    86: 'Cloak of the manta ray',
    87: 'Driftglobe',
    88: 'Goggles of night',
    89: 'Helm of comprehending languages',
    90: 'Immovable rod',
    91: 'Lantern of revealing',
    92: 'Mariner armor',
    93: 'Mithral armor',
    94: 'Potion of poison',
    95: 'Ring of swimming',
    96: 'Robe of useful items',
    97: 'Rope of climbing',
    98: 'Saddle of the cavalier',
    99: 'Wand of magic detection',
    100: 'Wand of secrets'
}

item_c = {
    range(1, 15): 'Potion of superior healing',
    range(16, 22): 'Spell scroll - 4th level',
    range(23, 27): 'Ammunition, +2',
    range(28, 32): 'Potion of clairvoyance',
    range(33, 37): 'Potion of diminution',
    range(38, 42): 'Potion of gaseous form',
    range(43, 47): 'Potion of frost giant strength',
    range(48, 52): 'Potion of stone giant strength',
    range(53, 57): 'Potion of heroism',
    range(58, 62): 'Potion of invulnerability',
    range(63, 67): 'Potion of mind reading',
    range(68, 72): 'Spell scroll - 5th level',
    range(73, 75): 'Elixer of health',
    range(76, 78): 'Oil of etherealness',
    range(79, 81): 'Potion of fire giant strength',
    range(82, 84): 'Quaal feather token',
    range(85, 87): 'Scroll of protection',
    range(88, 89): 'Bag of beans',
    range(90, 91): 'Bead of force',
    92: 'Chime of endless water',
    93: 'Decanter of endless water',
    94: 'Eyes of minute seeing',
    95: 'Folding boat',
    96: 'Heward handy haversack',
    97: 'Horseshoes of speed',
    98: 'Necklace of fireballs',
    99: 'Periapt of health',
    100: 'Sending stones'
}

item_d = {
    range(1, 20): 'Potion of supreme healing',
    range(21, 30): 'Potion of invisibility',
    range(31, 40): 'Potion of speed',
    range(41, 50): 'Spell scroll - 6th level',
    range(51, 57): 'Spell scroll - 7th level',
    range(58, 62): 'Ammunition, +3',
    range(63, 67): 'Oil of sharpness',
    range(68, 72): 'Potion of flying',
    range(73, 77): 'Potion of cloud giant strength',
    range(78, 82): 'Potion of longevity',
    range(83, 87): 'Potion of vitality',
    range(88, 92): 'Spell scroll - 8th level',
    range(93, 95): 'Horseshoes of zephyr',
    range(96, 98): 'Nolzur marvelous pigments',
    99: 'Bag of devouring',
    100: 'Portable hole'
}

item_e = {
    range(1, 30): 'Spell scroll - 8th level',
    range(31, 55): 'Potion of storm giant strength',
    range(56, 70): 'Potion of supreme healing',
    range(71, 85): 'Spell scroll - 9th level',
    range(86, 93): 'Universal solvent',
    range(94, 98): 'Arrow of slaying',
    range(99, 100): 'Sovereign glue'
}

item_f = {
    range(1, 15): 'Weapon, +1',
    range(16, 18): 'Shield, +1',
    range(19, 21): 'Sentinel shield',
    range(24, 25): 'Boots of elvenkind',
    range(26, 27): 'Boots of striding and springing',
    range(28, 29): 'Bracers of archery',
    range(30, 31): 'Brooch of shielding',
    range(32, 33): 'Broom of flying',
    range(34, 35): 'Cloak of elvenkind',
    range(36, 37): 'Cloak of protection',
    range(38, 39): 'Gauntlets of ogre power',
    range(40, 41): 'Hat of disguise',
    range(42, 43): 'Javelin of lightning',
    range(44, 45): 'Pearl of power',
    range(46, 47): 'Rod of the pact keeper, +1',
    range(48, 49): 'Slippers of spider climbing',
    range(50, 51): 'staff of the adder',
    range(52, 53): 'Staff of the python',
    range(54, 55): 'Sword of vengeance',
    range(56, 57): 'Trdient of fish command',
    range(58, 59): 'Want of magic missiles',
    range(60, 61): 'Wand of the war mage, +1',
    range(62, 63): 'Wand of web',
    range(64, 65): 'Weapon of warning',
    66: 'Adamantine chain male',
    67: 'Adamantine chain shirt',
    68: 'Adamantine scale male',
    69: 'Bag of tricks - gray',
    70: 'Bag of tricks - rust',
    71: 'Bag of tricks - tan',
    72: 'Boots of the winterlands',
    73: 'Circlet of blasting',
    74: 'Deck of illusions',
    75: 'Eversmoking bottle',
    76: 'Eyes of charming',
    77: 'Eyes of the eagle',
    78: 'Figurine of wondrous power - silver raven',
    79: 'Gem of brightness',
    80: 'Gloves of missile snaring',
    81: 'Gloves of swimming and climbing',
    82: 'Glove of thievery',
    83: 'Headband of intellect',
    84: 'Helm of telepathy',
    85: 'Doss lute of the bards',
    86: 'Fochlucan bandor of the bards',
    87: 'Mac-Fuimidh cittern of the bards',
    88: 'Medallion of thoughts',
    89: 'Necklace of adaptation',
    90: 'Periapt of wound closure',
    91: 'Pipes of haunting',
    92: 'Pipes of sewers',
    93: 'Ring of jumping',
    94: 'Ring of mind shielding',
    95: 'Ring of warmth',
    96: 'Ring of water walking',
    97: 'Quiver of Ehlonna',
    98: 'Stone of good luck',
    99: 'Wind fan',
    100: 'Winged boots'
}

item_g = {
    range(1, 11): 'Weapon, +2',
    15: 'Adamantine breastplate',
    16: 'Adamantine splint male',
    17: 'Amulet of health',
    18: 'Armor of vulnerability',
    19: 'Arrow-catching shiled',
    20: 'Belt of dwarvenkind',
    21: 'Belt of hill giant strength',
    22: 'Berserker axe',
    23: 'Boots of levitation',
    24: 'Boots of speed',
    25: 'Bowl of commanding water elementals',
    26: 'Bracers of defense',
    27: 'Brazier of commanding fire elementals',
    28: 'Cape of the mountebank',
    29: 'Censer of controlling air elementals',
    30: 'Armor, +1 chain male',
    31: 'Chain male of resistance',
    32: 'Armor, +1 chain shirt',
    33: 'Chain shirt of resistance',
    34: 'Cloak of displacement',
    35: 'Cloak of the bat',
    36: 'Cube of force',
    37: 'Daern instant fortress',
    38: 'Dagger of venom',
    39: 'Dimensional shackles',
    40: 'Dragon slayer',
    41: 'Elven chain',
    42: 'Flame tongue',
    43: 'Gem of seeing',
    44: 'Giant slayer',
    45: 'Glamoured studded leather',
    46: 'Helm of teleportation',
    47: 'Horn of blasting',
    48: 'Horn of Valhalla - silver or brass',
    49: 'Canaith mandolin of the bards',
    50: 'Lyre of the bards',
    51: 'Stone of awareness',
    52: 'Stone of protection',
    53: 'Stone of reserve',
    54: 'Stone of sustenance',
    55: 'Iron bands of Bilarro',
    56: 'Armor, +1 leather',
    57: 'Armor of resistance (leather',
    58: 'Mace of disruption',
    60: 'Mace of smiting',
    61: 'Mantle of spell resistance',
    62: 'Necklace of prayer',
    63: 'Periapt of proof against poison',
    64: 'Ring of animal influence',
    65: 'Ring of evasion',
    66: 'Ring of feather falling',
    67: 'Ring of free action',
    68: 'Ring of protection',
    69: 'Ring of resistance',
    70: 'Ring of spell storing',
    71: 'Ring of the ram',
    72: 'Ring of x-ray vision',
    73: 'Robe of eyes',
    74: 'Rod of ruleship',
    75: 'Rod of the pact keeper, +2',
    76: 'Rope of entanglement',
    77: 'Armor, +1 scale mail',
    78: 'Scale mail of resistance',
    79: 'Shield, +2',
    80: 'Shield of missile attraction',
    81: 'Staff of charming',
    82: 'Staff of healing',
    83: 'Staff of swarming insects',
    84: 'Staff of the woodlands',
    85: 'Staff of withering',
    86: 'Stone of controlling earth elementals',
    87: 'Sun blade',
    88: 'Sword of life stealing',
    89: 'Sword of wounding',
    90: 'Tentacle rod',
    91: 'Vicious weapon',
    92: 'Wand of blinding',
    93: 'Wand of enemy detection',
    94: 'Wand of fear',
    95: 'Wand of fireballs',
    96: 'Wand of lightning bolts',
    97: 'Wand of paralysis',
    98: 'Wand of the war mage, +2',
    99: 'Wand of wonder',
    100: 'Wings of flying'
}

item_g_12 = {
    1: 'Figurine of wondrous power - bronze griffon',
    2: 'Figurine of wondrous power - ebony fly',
    3: 'Figurine of wondrous power - golden lions',
    4: 'Figurine of wondrous power - ivory goats',
    5: 'Figurine of wondrous power - marble elephant',
    range(6, 7): 'Figurine of wondrous power - onyx dog',
    8: 'Figurine of wondrous power - serpentine owl',
}

item_h = {
    range(1, 11): 'Weapon, +3',
    range(11, 13): 'Amulet of the planes',
    range(13, 15): 'Carpet of flying',
    range(15, 17): 'Crystal ball (very rare version',
    range(17, 19): 'Ring of regeneration',
    range(19, 21): 'Ring of shooting stars',
    range(21, 23): 'Ring of telekinesis',
    range(23, 25): 'Robe of scintillating colors',
    range(25, 27): 'Robe of stars',
    range(27, 29): 'Rod of absorption',
    range(29, 31): 'Rod of alertness',
    range(31, 33): 'Rod of security',
    range(33, 35): 'Rod of the pact keeper, +3',
    range(35, 37): 'Scimitar of speed',
    range(37, 39): 'Shield, +3',
    range(39, 41): 'Staff of fire',
    range(41, 43): 'Staff of frost',
    range(43, 45): 'Staff of power',
    range(45, 47): 'Staff of striking',
    range(47, 49): 'Staff of thunder and lightning',
    range(49, 51): 'Sword of sharpness',
    range(51, 53): 'Wand of polymorph',
    range(53, 55): 'Wand of the war mage, +3',
    55: 'Adamantine half plate',
    56: 'Adamantine full plate',
    57: 'Animated shield',
    58: 'Belt of fire giant strength',
    59: 'Belt of frost (or stone giant strength',
    60: 'Breastplate, +1',
    61: 'Candle of invocation',
    62: 'Chainmail, +2',
    63: 'Chain shirt, +2',
    64: 'Cloak of arachnida',
    65: 'Dancing sword',
    66: 'Demon armor',
    67: 'Dragon scale mail',
    68: 'Dwarven plate',
    69: 'Dwarven thrower',
    70: 'Efreeti bottle',
    71: 'Figurine of wondrous power (obsidian steed',
    72: 'Frost brand',
    73: 'Helm of brilliance',
    74: 'Horn of Valhalla (bronze',
    75: 'Anstruth harp of the bards',
    76: 'Stone of absorption',
    77: 'Stone of agility',
    78: 'Stone of fortitude',
    79: 'Stone of insight',
    80: 'Stone of intellect',
    81: 'Stone of leadership',
    82: 'Stone of strength',
    83: 'Armor, +2 leather',
    84: 'Manual of bodily health',
    85: 'Manual of gainful exercise',
    86: 'Manual of golems',
    87: 'Manual of quickness of action',
    88: 'Mirror of life trapping',
    89: 'Nine lives stealer',
    90: 'Oathbow',
    91: 'Scale mail, +2',
    92: 'Spellguard shield',
    93: 'Armor, +1 splint',
    94: 'Splint armor of resistance',
    95: 'Studded leather armor, +1',
    96: 'Studded leather armor of resistance',
    97: 'tome of clear thought',
    98: 'Tome of leadership',
    99: 'Tome of understanding',
   100: 'Tome of righteousness'
}

item_i = {
    range(1, 6): 'Defender',
    range(6, 11): 'Hammer of thunderbolts',
    range(11, 16): 'Luck blade',
    range(16, 21): 'Sword of answering',
    range(21, 24): 'Holy avenger',
    range(24, 27): 'Ring of djinni summoning',
    range(27, 30): 'Ring of invisibility',
    range(30, 33): 'Ring of spell turning',
    range(33, 36): 'Rod of lordly might',
    range(36, 39): 'Staff of the magi',
    range(39, 42): 'Vorpal sword',
    range(42, 44): 'Belt of cloud giant strength',
    range(44, 46): 'Breastplate, +2',
    range(46, 48): 'Chain mail, +3',
    range(48, 50): 'Chain shirt, +3',
    range(50, 52): 'Cloak of invisibility',
    range(52, 54): 'Crystal ball (legendary version',
    range(54, 56): 'Half plate, +1',
    range(56, 58): 'Iron flask',
    range(58, 60): 'Leather armor, +3',
    range(60, 62): 'Plate armor, +1',
    range(62, 64): 'Robe of the archmagi',
    range(64, 66): 'Rod of ressurection',
    range(66, 68): 'Scale mail, +1',
    range(68, 70): 'Scarab of protection',
    range(70, 72): 'Splint armor, +2',
    range(72, 74): 'Studded leather armor, +2',
    range(74, 77): 'Well of many worlds',
    77: 'Apparatus of Kwalish',
    78: 'Armor of invulnerability',
    79: 'Belt of storm giant strength',
    80: 'Cubic gate',
    81: 'Deck of many things',
    82: 'Efretti chain',
    83: 'Half plate armor of resistance',
    84: 'Horn of Valhalla (iron',
    85: 'Ollamh harp of the bards',
    86: 'Stone of greater absorption',
    87: 'Stone of mastery',
    88: 'Stone of regeneration',
    89: 'Plate armor of etherealness',
    90: 'Plate armor of resistance',
    91: 'Ring of air elemental command',
    92: 'Ring of earth elemental command',
    93: 'Ring of fire elemental command',
    94: 'Ring of three wishes',
    95: 'Ring of water elemental command',
    96: 'Sphere of annihilation',
    97: 'Talisman of pure good',
    98: 'Talisman of the sphere',
    99: 'Talisman of ultimate evil',
    100: 'Tome of the stilled tongue'
}

item_i_76 = {
    range(1, 3): 'Half plate, +2',
    range(3, 5): 'Plate armor, +2',
    range(5, 7): 'Studded leather armor, +3',
    range(7, 9): 'Breastplate, +3',
    range(9, 11): 'Splint armor, +3',
    11: 'Half plate armor, +3',
    12: 'Full plate armor, +3'
}

import dice

# Looks up the maximum item value from the dict.key that is passed 
# Rolls the dice with '1d' + the '*max' value
# Looks up loot from dict and returns value
def get_treasure_values(treasure_dict):
    roll_size = list(treasure_dict.keys())[-1]
    roll_result = dice.roll('1d'+str(roll_size))
    treasure_values = []
    print('Rolling (1d' + str(roll_size) + ') Result:' + str(roll_result))
    for numrange, description in treasure_dict.items():
        if type(numrange) == range:
            for _num in numrange:
                treasure_values.append(description)
        else:
            treasure_values.append(description)
    return  'You received a ' + treasure_values[roll_result[0]-1]


